# Generated by Django 4.1.7 on 2023-05-01 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='programa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.programa'),
        ),
    ]
