# Generated by Django 4.1.7 on 2023-05-02 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_asistenciaevento'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_registradas', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('actividad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.actividad')),
                ('estudiante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.estudiante')),
            ],
        ),
    ]
