# Generated by Django 4.1.7 on 2023-05-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_tarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='minuto',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='task_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
