# Generated by Django 4.1.7 on 2023-05-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_tarea_minuto_alter_tarea_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='dia',
            field=models.IntegerField(null=True),
        ),
    ]
